# Q1. Problem Statement: Understanding Array Functions

Write a Python program that takes the speeds of any vehicle to store it in a 
NumPy array and calculates the average speed.

Note: Use NumPy functions to get the desired output.

In [38]:
import numpy as np

x = int(input("What numer of speeds do you want to enter?" ))
speed_list = []
for y in range(x):
    z = int(input("Enter the speeds in Km/hr: "))
    speed_list.append(z)

speed_array = np.array(speed_list)
print("The average speed is: ", speed_array.sum()/len(speed_list))

What numer of speeds do you want to enter? 20
Enter the speeds in Km/hr:  61
Enter the speeds in Km/hr:  63
Enter the speeds in Km/hr:  64
Enter the speeds in Km/hr:  65
Enter the speeds in Km/hr:  66
Enter the speeds in Km/hr:  76
Enter the speeds in Km/hr:  78
Enter the speeds in Km/hr:  78
Enter the speeds in Km/hr:  98
Enter the speeds in Km/hr:  68
Enter the speeds in Km/hr:  98
Enter the speeds in Km/hr:  56
Enter the speeds in Km/hr:  79
Enter the speeds in Km/hr:  57
Enter the speeds in Km/hr:  78
Enter the speeds in Km/hr:  54
Enter the speeds in Km/hr:  74
Enter the speeds in Km/hr:  83
Enter the speeds in Km/hr:  93
Enter the speeds in Km/hr:  100


The average speed is:  74.45


# Q2. Problem Statement: Array Indexing/Slicing
Write a Python program to generate a 3-D array with integers of your choice, 
perform indexing, and print the first two rows and last two columns of the array
.
Note: Use NumPy arange() function to generate a random array.

In [37]:
import numpy as np

arr = np.arange(0,106,3).reshape(6,6)
print("The array is: \n", arr)
print("The first two rows are: \n", arr[:2])
print("The last two columns are: \n", arr[:,-2:])

The array is: 
 [[  0   3   6   9  12  15]
 [ 18  21  24  27  30  33]
 [ 36  39  42  45  48  51]
 [ 54  57  60  63  66  69]
 [ 72  75  78  81  84  87]
 [ 90  93  96  99 102 105]]
The first two rows are: 
 [[ 0  3  6  9 12 15]
 [18 21 24 27 30 33]]
The last two columns are: 
 [[ 12  15]
 [ 30  33]
 [ 48  51]
 [ 66  69]
 [ 84  87]
 [102 105]]
