# Q1. Problem Statement: Understanding Array Manipulation - I

Define a NumPy array with 4 * 5 dimensions, and swap the array's dimensions to 
make it  5 *4 using suitable functions..

In [7]:
import numpy as np

arr = np.arange(20, 40)
print("Original Array: \n", arr)

arr2 = arr.reshape(4,5)
print("Reshape Array: \n", arr2)

print("Transpose o Array: \n", arr2.transpose())

Original Array: 
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
Reshape Array: 
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
Transpose o Array: 
 [[20 25 30 35]
 [21 26 31 36]
 [22 27 32 37]
 [23 28 33 38]
 [24 29 34 39]]


# Q2. Problem Statement: Understanding Array Manipulation - II

Write a Python program to create two 2-dimensional arrays and apply
hstack(), vstack(), concatenate(), and split() functions to 
them to get the output as shown below..

In [33]:
import numpy as np

x = np.arange(22,26).reshape(2,2)
y = np.arange(11, 15).reshape(2,2)
z = np.concatenate((x, y))
print("First array is: \n", x)
print("Second array is: \n", y)

print("Applying hstack() function: \n", np.hstack((x, y)))
print("Applying vstack() function: \n", np.vstack((x, y)))
print("Applying concetenate() function: \n", np.concatenate((x, y)))
print("Applying split() function: \n",np.split(z,2,axis=0))

First array is: 
 [[22 23]
 [24 25]]
Second array is: 
 [[11 12]
 [13 14]]
Applying hstack() function: 
 [[22 23 11 12]
 [24 25 13 14]]
Applying vstack() function: 
 [[22 23]
 [24 25]
 [11 12]
 [13 14]]
Applying concetenate() function: 
 [[22 23]
 [24 25]
 [11 12]
 [13 14]]
Applying split() function: 
 [array([[22, 23],
       [24, 25]]), array([[11, 12],
       [13, 14]])]
